version: '3.7'

services:
  toolpad:
    image: muicom/toolpad:${TAG}
    environment:
      - TOOLPAD_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?connect_timeout=10
      - TOOLPAD_ENABLE_CREATE_BY_DOM=1
      - PORT=3000
      - EXTERNAL_URL=http://localhost:3000/
    ports:
      - '3000:3000'

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    expose:
      - '5432'
