version: '3.9'

services:
  toolpad:
    image: muicom/toolpad:${TAG}
    environment:
      - TOOLPAD_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?connect_timeout=10
      - TOOLPAD_ENABLE_CREATE_BY_DOM=1
      - PORT=3000
      - TOOLPAD_EXTERNAL_URL=http://toolpad:3000/
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    expose:
      - '5432'

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - '80'

  playwright:
    profiles:
      - test
    image: mcr.microsoft.com/playwright:v1.29.1-focal
    environment:
      - PLAYWRIGHT_TEST_BASE_URL=http://toolpad:3000/
      - HTTPBIN_BASEURL=http://httpbin/
    working_dir: /tests
    volumes:
      - .:/tests
    command: yarn test:integration --forbid-only
