# https://render.com/docs/preview-environments
previewsEnabled: false

services:
  - type: web
    name: toolpad-app
    env: node
    buildCommand: yarn --frozen-lockfile --prod=false && yarn release:build
    startCommand: yarn start
    healthCheckPath: /health-check
    plan: free
    # previewPlan: free
    # can't have preview environments on free plan but maybe this:
    pullRequestPreviewsEnabled: true
    envVars:
      - key: STUDIO_DATABASE_URL
        fromDatabase:
          name: toolpad-db
          property: connectionString
      - fromGroup: toolpad-settings

databases:
  - name: toolpad-db
    ipAllowList: []
    plan: free
    # previewPlan: free

envVarGroups:
  - name: toolpad-settings
    envVars:
      - key: STUDIO_BASIC_AUTH_USER
        sync: false
      - key: STUDIO_BASIC_AUTH_PASSWORD
        sync: false
