# https://render.com/docs/preview-environments
previewsEnabled: true
previewsExpireAfterDays: 3

services:
  - type: web
    name: toolpad
    env: node
    buildCommand: yarn --frozen-lockfile --prod=false && yarn release:build
    startCommand: yarn start
    healthCheckPath: /health-check
    plan: starter plus
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: '18.10.0'
      - key: TOOLPAD_ENABLE_CREATE_BY_DOM
        value: null
        previewValue: '1'
      - key: TOOLPAD_DATABASE_URL
        fromDatabase:
          name: toolpad-db
          property: connectionString
      - fromGroup: toolpad-settings
    buildFilter:
      ignoredPaths:
        - docs/**
        - '**/*.spec.ts'

databases:
  - name: toolpad-db
    ipAllowList: []
    plan: starter

envVarGroups:
  - name: toolpad-settings
    envVars:
      - key: TOOLPAD_BASIC_AUTH_USER
        sync: false
      - key: TOOLPAD_BASIC_AUTH_PASSWORD
        sync: false
