# test
# https://render.com/docs/preview-environments
previewsEnabled: false
previewsExpireAfterDays: 3

services:
  - type: web
    name: toolpad
    env: node
    buildCommand: yarn --frozen-lockfile --prod=false && yarn release:build
    startCommand: yarn start
    healthCheckPath: /health-check
    plan: starter plus
    # previewPlan: free
    pullRequestPreviewsEnabled: true
    envVars:
      - key: STUDIO_DATABASE_URL
        fromDatabase:
          name: toolpad-db
          property: connectionString
      - fromGroup: toolpad-settings

databases:
  - name: toolpad-db
    ipAllowList: []
    plan: starter
    # previewPlan: free

envVarGroups:
  - name: toolpad-settings
    envVars:
      - key: STUDIO_BASIC_AUTH_USER
        sync: false
      - key: STUDIO_BASIC_AUTH_PASSWORD
        sync: false
