name: Update monorepo

on: workflow_dispatch

permissions: {}

jobs:
  update-monorepo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Set up Node.js ⚙️
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: '18.x'

      - name: Setup yarn
        run: npm install -g yarn

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Get latest monorepo commit
        run: echo "MONOREPO_LATEST_COMMIT=$(git ls-remote https://github.com/mui/material-ui master | awk '{print $1}')" >> $GITHUB_ENV
